# Generated by Django 5.2.10 on 2026-01-25 18:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply', '0002_alter_fornecedor_cnpj_alter_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.IntegerField(verbose_name='Número da nota fiscal')),
                ('issue_date', models.DateField(default=datetime.datetime.now, verbose_name='Data de emissão')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('product_category', models.CharField(max_length=255, verbose_name='Categoria do produto')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Valor total')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Item da nota fiscal de compra',
                'verbose_name_plural': 'Itens da nota fiscal de compra',
            },
        ),
    ]
