# Generated by Django 5.2.10 on 2026-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabil', '0002_alter_purchaseinvoiceitems_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitems',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade'),
        ),
    ]
