# Generated by Django 5.2.10 on 2026-01-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabil', '0003_alter_purchaseinvoiceitems_quantity'),
        ('financial', '0002_rename_supply_accountpayable_supplier'),
        ('supply', '0003_rename_fornecedor_supplier_rename_nome_supplier_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseInvoiceItems',
            new_name='Invoice',
        ),
    ]
