# Generated by Django 5.2.10 on 2026-01-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabil', '0003_alter_purchaseinvoiceitems_quantity'),
        ('financial', '0001_initial'),
        ('supply', '0002_alter_fornecedor_cnpj_alter_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedor',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='telefone',
            new_name='phone',
        ),
    ]
