# Generated by Django 5.2.10 on 2026-01-25 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabil', '0003_alter_purchaseinvoiceitems_quantity'),
        ('supply', '0002_alter_fornecedor_cnpj_alter_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('invoices', models.ManyToManyField(blank=True, related_name='account_payable', to='contabil.purchaseinvoiceitems', verbose_name='Notas Fiscais')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_payable', to='supply.fornecedor', verbose_name='Fornecedor')),
            ],
        ),
    ]
