# Generated by Django 5.2.10 on 2026-01-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpayable',
            old_name='supply',
            new_name='supplier',
        ),
    ]
